# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Aug 24 23:38:32 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 750)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 750))
        MainWindow.setMaximumSize(QtCore.QSize(870, 750))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.CaptionBox = QtGui.QGroupBox(self.centralwidget)
        self.CaptionBox.setMinimumSize(QtCore.QSize(70, 0))
        self.CaptionBox.setMaximumSize(QtCore.QSize(70, 700))
        self.CaptionBox.setTitle(_fromUtf8(""))
        self.CaptionBox.setFlat(True)
        self.CaptionBox.setObjectName(_fromUtf8("CaptionBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.CaptionBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_22 = QtGui.QLabel(self.CaptionBox)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_3.addWidget(self.label_22)
        spacerItem = QtGui.QSpacerItem(20, 52, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtGui.QLabel(self.CaptionBox)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(20, 27, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_18 = QtGui.QLabel(self.CaptionBox)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.CaptionBox)
        self.label_19.setMinimumSize(QtCore.QSize(0, 40))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.CaptionBox)
        self.label_20.setMinimumSize(QtCore.QSize(0, 40))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_3.addWidget(self.label_20)
        spacerItem2 = QtGui.QSpacerItem(20, 44, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.SubButton = QtGui.QPushButton(self.CaptionBox)
        self.SubButton.setCheckable(True)
        self.SubButton.setObjectName(_fromUtf8("SubButton"))
        self.verticalLayout_3.addWidget(self.SubButton)
        spacerItem3 = QtGui.QSpacerItem(20, 95, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.label_21 = QtGui.QLabel(self.CaptionBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 100))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 400))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_3.addWidget(self.label_21)
        spacerItem4 = QtGui.QSpacerItem(20, 51, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3.addWidget(self.CaptionBox)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.MicModeButton = QtGui.QPushButton(self.centralwidget)
        self.MicModeButton.setObjectName(_fromUtf8("MicModeButton"))
        self.horizontalLayout_2.addWidget(self.MicModeButton)
        spacerItem6 = QtGui.QSpacerItem(222, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Mic1 = QtGui.QGroupBox(self.centralwidget)
        self.Mic1.setMinimumSize(QtCore.QSize(90, 0))
        self.Mic1.setMaximumSize(QtCore.QSize(90, 700))
        self.Mic1.setAlignment(QtCore.Qt.AlignCenter)
        self.Mic1.setFlat(False)
        self.Mic1.setCheckable(False)
        self.Mic1.setProperty("channel", _fromUtf8(""))
        self.Mic1.setObjectName(_fromUtf8("Mic1"))
        self.gridLayout = QtGui.QGridLayout(self.Mic1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        self.Mic1Pan = QtGui.QDial(self.Mic1)
        self.Mic1Pan.setMinimumSize(QtCore.QSize(40, 40))
        self.Mic1Pan.setMaximumSize(QtCore.QSize(40, 40))
        self.Mic1Pan.setMaximum(127)
        self.Mic1Pan.setProperty("value", 0)
        self.Mic1Pan.setSliderPosition(0)
        self.Mic1Pan.setWrapping(False)
        self.Mic1Pan.setObjectName(_fromUtf8("Mic1Pan"))
        self.gridLayout.addWidget(self.Mic1Pan, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1PanLcd = QtGui.QLCDNumber(self.Mic1)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Mic1PanLcd.setFont(font)
        self.Mic1PanLcd.setNumDigits(3)
        self.Mic1PanLcd.setObjectName(_fromUtf8("Mic1PanLcd"))
        self.gridLayout.addWidget(self.Mic1PanLcd, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton = QtGui.QRadioButton(self.Mic1)
        self.radioButton.setEnabled(False)
        self.radioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.radioButton.setMaximumSize(QtCore.QSize(20, 20))
        self.radioButton.setText(_fromUtf8(""))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1Ins1 = QtGui.QDial(self.Mic1)
        self.Mic1Ins1.setMinimumSize(QtCore.QSize(40, 40))
        self.Mic1Ins1.setMaximumSize(QtCore.QSize(40, 40))
        self.Mic1Ins1.setMaximum(127)
        self.Mic1Ins1.setProperty("value", 0)
        self.Mic1Ins1.setSliderPosition(0)
        self.Mic1Ins1.setObjectName(_fromUtf8("Mic1Ins1"))
        self.gridLayout.addWidget(self.Mic1Ins1, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1Ins2 = QtGui.QDial(self.Mic1)
        self.Mic1Ins2.setMinimumSize(QtCore.QSize(40, 40))
        self.Mic1Ins2.setMaximumSize(QtCore.QSize(40, 40))
        self.Mic1Ins2.setMaximum(127)
        self.Mic1Ins2.setObjectName(_fromUtf8("Mic1Ins2"))
        self.gridLayout.addWidget(self.Mic1Ins2, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1SubContainer = QtGui.QFrame(self.Mic1)
        self.Mic1SubContainer.setMinimumSize(QtCore.QSize(80, 150))
        self.Mic1SubContainer.setMaximumSize(QtCore.QSize(80, 150))
        self.Mic1SubContainer.setFrameShape(QtGui.QFrame.NoFrame)
        self.Mic1SubContainer.setFrameShadow(QtGui.QFrame.Plain)
        self.Mic1SubContainer.setObjectName(_fromUtf8("Mic1SubContainer"))
        self.gridLayout_6 = QtGui.QGridLayout(self.Mic1SubContainer)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.Mic1SubFader = QtGui.QSlider(self.Mic1SubContainer)
        self.Mic1SubFader.setMinimumSize(QtCore.QSize(0, 100))
        self.Mic1SubFader.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Mic1SubFader.setMaximum(127)
        self.Mic1SubFader.setOrientation(QtCore.Qt.Vertical)
        self.Mic1SubFader.setObjectName(_fromUtf8("Mic1SubFader"))
        self.gridLayout_6.addWidget(self.Mic1SubFader, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1SubLcd = QtGui.QLCDNumber(self.Mic1SubContainer)
        self.Mic1SubLcd.setNumDigits(3)
        self.Mic1SubLcd.setObjectName(_fromUtf8("Mic1SubLcd"))
        self.gridLayout_6.addWidget(self.Mic1SubLcd, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.Mic1SubContainer, 6, 0, 1, 1)
        self.Mic1Mute = QtGui.QPushButton(self.Mic1)
        self.Mic1Mute.setStyleSheet(_fromUtf8("QPushButton#Mic1Mute:checked { background-color: red}"))
        self.Mic1Mute.setCheckable(True)
        self.Mic1Mute.setObjectName(_fromUtf8("Mic1Mute"))
        self.gridLayout.addWidget(self.Mic1Mute, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1Solo = QtGui.QPushButton(self.Mic1)
        self.Mic1Solo.setStyleSheet(_fromUtf8("QPushButton#Mic1Solo:checked { background-color: red}"))
        self.Mic1Solo.setCheckable(True)
        self.Mic1Solo.setObjectName(_fromUtf8("Mic1Solo"))
        self.gridLayout.addWidget(self.Mic1Solo, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1Fader = QtGui.QSlider(self.Mic1)
        self.Mic1Fader.setMinimumSize(QtCore.QSize(0, 150))
        self.Mic1Fader.setMaximumSize(QtCore.QSize(16777215, 400))
        self.Mic1Fader.setMaximum(127)
        self.Mic1Fader.setOrientation(QtCore.Qt.Vertical)
        self.Mic1Fader.setObjectName(_fromUtf8("Mic1Fader"))
        self.gridLayout.addWidget(self.Mic1Fader, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic1Lcd = QtGui.QLCDNumber(self.Mic1)
        self.Mic1Lcd.setObjectName(_fromUtf8("Mic1Lcd"))
        self.gridLayout.addWidget(self.Mic1Lcd, 10, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtGui.QLabel(self.Mic1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 11, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Mic1)
        self.Mic2 = QtGui.QGroupBox(self.centralwidget)
        self.Mic2.setMinimumSize(QtCore.QSize(90, 0))
        self.Mic2.setMaximumSize(QtCore.QSize(90, 700))
        self.Mic2.setAlignment(QtCore.Qt.AlignCenter)
        self.Mic2.setFlat(False)
        self.Mic2.setCheckable(False)
        self.Mic2.setObjectName(_fromUtf8("Mic2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Mic2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Mic2Ins1 = QtGui.QDial(self.Mic2)
        self.Mic2Ins1.setMinimumSize(QtCore.QSize(40, 40))
        self.Mic2Ins1.setMaximumSize(QtCore.QSize(40, 40))
        self.Mic2Ins1.setMaximum(127)
        self.Mic2Ins1.setObjectName(_fromUtf8("Mic2Ins1"))
        self.gridLayout_2.addWidget(self.Mic2Ins1, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2Pan = QtGui.QDial(self.Mic2)
        self.Mic2Pan.setMinimumSize(QtCore.QSize(40, 40))
        self.Mic2Pan.setMaximumSize(QtCore.QSize(40, 40))
        self.Mic2Pan.setMaximum(127)
        self.Mic2Pan.setProperty("value", 0)
        self.Mic2Pan.setSliderPosition(0)
        self.Mic2Pan.setWrapping(False)
        self.Mic2Pan.setObjectName(_fromUtf8("Mic2Pan"))
        self.gridLayout_2.addWidget(self.Mic2Pan, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2Lcd = QtGui.QLCDNumber(self.Mic2)
        self.Mic2Lcd.setObjectName(_fromUtf8("Mic2Lcd"))
        self.gridLayout_2.addWidget(self.Mic2Lcd, 11, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtGui.QLabel(self.Mic2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 14, 0, 1, 1)
        self.Mic2PanLcd = QtGui.QLCDNumber(self.Mic2)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Mic2PanLcd.setFont(font)
        self.Mic2PanLcd.setNumDigits(3)
        self.Mic2PanLcd.setObjectName(_fromUtf8("Mic2PanLcd"))
        self.gridLayout_2.addWidget(self.Mic2PanLcd, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2Fader = QtGui.QSlider(self.Mic2)
        self.Mic2Fader.setMinimumSize(QtCore.QSize(0, 100))
        self.Mic2Fader.setMaximumSize(QtCore.QSize(16777215, 400))
        self.Mic2Fader.setMaximum(127)
        self.Mic2Fader.setOrientation(QtCore.Qt.Vertical)
        self.Mic2Fader.setObjectName(_fromUtf8("Mic2Fader"))
        self.gridLayout_2.addWidget(self.Mic2Fader, 10, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2Mute = QtGui.QPushButton(self.Mic2)
        self.Mic2Mute.setStyleSheet(_fromUtf8("QPushButton#Mic2Mute:checked { background-color: red}"))
        self.Mic2Mute.setCheckable(True)
        self.Mic2Mute.setObjectName(_fromUtf8("Mic2Mute"))
        self.gridLayout_2.addWidget(self.Mic2Mute, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem8, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.Mic2)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.radioButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.radioButton_2.setText(_fromUtf8(""))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_2.addWidget(self.radioButton_2, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2Solo = QtGui.QPushButton(self.Mic2)
        self.Mic2Solo.setStyleSheet(_fromUtf8("QPushButton#Mic2Solo:checked { background-color: red}"))
        self.Mic2Solo.setCheckable(True)
        self.Mic2Solo.setObjectName(_fromUtf8("Mic2Solo"))
        self.gridLayout_2.addWidget(self.Mic2Solo, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2Ins2 = QtGui.QDial(self.Mic2)
        self.Mic2Ins2.setMinimumSize(QtCore.QSize(40, 40))
        self.Mic2Ins2.setMaximumSize(QtCore.QSize(40, 40))
        self.Mic2Ins2.setMaximum(127)
        self.Mic2Ins2.setObjectName(_fromUtf8("Mic2Ins2"))
        self.gridLayout_2.addWidget(self.Mic2Ins2, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2SubContainer = QtGui.QFrame(self.Mic2)
        self.Mic2SubContainer.setMinimumSize(QtCore.QSize(80, 150))
        self.Mic2SubContainer.setMaximumSize(QtCore.QSize(80, 150))
        self.Mic2SubContainer.setFrameShape(QtGui.QFrame.NoFrame)
        self.Mic2SubContainer.setFrameShadow(QtGui.QFrame.Plain)
        self.Mic2SubContainer.setObjectName(_fromUtf8("Mic2SubContainer"))
        self.gridLayout_10 = QtGui.QGridLayout(self.Mic2SubContainer)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.Mic2SubFader = QtGui.QSlider(self.Mic2SubContainer)
        self.Mic2SubFader.setMinimumSize(QtCore.QSize(0, 100))
        self.Mic2SubFader.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Mic2SubFader.setMaximum(127)
        self.Mic2SubFader.setOrientation(QtCore.Qt.Vertical)
        self.Mic2SubFader.setObjectName(_fromUtf8("Mic2SubFader"))
        self.gridLayout_10.addWidget(self.Mic2SubFader, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Mic2SubLcd = QtGui.QLCDNumber(self.Mic2SubContainer)
        self.Mic2SubLcd.setNumDigits(3)
        self.Mic2SubLcd.setObjectName(_fromUtf8("Mic2SubLcd"))
        self.gridLayout_10.addWidget(self.Mic2SubLcd, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.Mic2SubContainer, 6, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Mic2)
        self.Wave1 = QtGui.QGroupBox(self.centralwidget)
        self.Wave1.setMinimumSize(QtCore.QSize(90, 0))
        self.Wave1.setMaximumSize(QtCore.QSize(90, 700))
        self.Wave1.setObjectName(_fromUtf8("Wave1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Wave1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Wave1Mute = QtGui.QPushButton(self.Wave1)
        self.Wave1Mute.setStyleSheet(_fromUtf8("QPushButton#Wave1Mute:checked { background-color: red}"))
        self.Wave1Mute.setCheckable(True)
        self.Wave1Mute.setObjectName(_fromUtf8("Wave1Mute"))
        self.gridLayout_3.addWidget(self.Wave1Mute, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_3 = QtGui.QRadioButton(self.Wave1)
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setMinimumSize(QtCore.QSize(20, 20))
        self.radioButton_3.setMaximumSize(QtCore.QSize(20, 20))
        self.radioButton_3.setText(_fromUtf8(""))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_3.addWidget(self.radioButton_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave1Ins1 = QtGui.QDial(self.Wave1)
        self.Wave1Ins1.setMinimumSize(QtCore.QSize(40, 40))
        self.Wave1Ins1.setMaximumSize(QtCore.QSize(40, 40))
        self.Wave1Ins1.setMaximum(127)
        self.Wave1Ins1.setObjectName(_fromUtf8("Wave1Ins1"))
        self.gridLayout_3.addWidget(self.Wave1Ins1, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave1Solo = QtGui.QPushButton(self.Wave1)
        self.Wave1Solo.setStyleSheet(_fromUtf8("QPushButton#Wave1Solo:checked { background-color: red}"))
        self.Wave1Solo.setCheckable(True)
        self.Wave1Solo.setObjectName(_fromUtf8("Wave1Solo"))
        self.gridLayout_3.addWidget(self.Wave1Solo, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem9 = QtGui.QSpacerItem(20, 92, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem9, 0, 0, 1, 1)
        self.Wave1Ins2 = QtGui.QDial(self.Wave1)
        self.Wave1Ins2.setMinimumSize(QtCore.QSize(40, 40))
        self.Wave1Ins2.setMaximumSize(QtCore.QSize(40, 40))
        self.Wave1Ins2.setMaximum(127)
        self.Wave1Ins2.setObjectName(_fromUtf8("Wave1Ins2"))
        self.gridLayout_3.addWidget(self.Wave1Ins2, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave1Fader = QtGui.QSlider(self.Wave1)
        self.Wave1Fader.setMinimumSize(QtCore.QSize(0, 100))
        self.Wave1Fader.setMaximumSize(QtCore.QSize(16777215, 400))
        self.Wave1Fader.setMaximum(127)
        self.Wave1Fader.setProperty("value", 0)
        self.Wave1Fader.setOrientation(QtCore.Qt.Vertical)
        self.Wave1Fader.setProperty("channel", 0)
        self.Wave1Fader.setProperty("parameter", 0)
        self.Wave1Fader.setObjectName(_fromUtf8("Wave1Fader"))
        self.gridLayout_3.addWidget(self.Wave1Fader, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtGui.QLabel(self.Wave1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 13, 0, 1, 1)
        self.Wave1Lcd = QtGui.QLCDNumber(self.Wave1)
        self.Wave1Lcd.setObjectName(_fromUtf8("Wave1Lcd"))
        self.gridLayout_3.addWidget(self.Wave1Lcd, 10, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave1SubContainer = QtGui.QFrame(self.Wave1)
        self.Wave1SubContainer.setMinimumSize(QtCore.QSize(80, 150))
        self.Wave1SubContainer.setMaximumSize(QtCore.QSize(80, 150))
        self.Wave1SubContainer.setFrameShape(QtGui.QFrame.NoFrame)
        self.Wave1SubContainer.setFrameShadow(QtGui.QFrame.Plain)
        self.Wave1SubContainer.setObjectName(_fromUtf8("Wave1SubContainer"))
        self.gridLayout_11 = QtGui.QGridLayout(self.Wave1SubContainer)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.Wave1SubFader = QtGui.QSlider(self.Wave1SubContainer)
        self.Wave1SubFader.setMinimumSize(QtCore.QSize(0, 100))
        self.Wave1SubFader.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Wave1SubFader.setMaximum(127)
        self.Wave1SubFader.setOrientation(QtCore.Qt.Vertical)
        self.Wave1SubFader.setObjectName(_fromUtf8("Wave1SubFader"))
        self.gridLayout_11.addWidget(self.Wave1SubFader, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave1SubLcd = QtGui.QLCDNumber(self.Wave1SubContainer)
        self.Wave1SubLcd.setNumDigits(3)
        self.Wave1SubLcd.setObjectName(_fromUtf8("Wave1SubLcd"))
        self.gridLayout_11.addWidget(self.Wave1SubLcd, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addWidget(self.Wave1SubContainer, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Wave1)
        self.Wave2 = QtGui.QGroupBox(self.centralwidget)
        self.Wave2.setMinimumSize(QtCore.QSize(90, 0))
        self.Wave2.setMaximumSize(QtCore.QSize(90, 700))
        self.Wave2.setObjectName(_fromUtf8("Wave2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.Wave2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.Wave2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 12, 0, 1, 1)
        self.Wave2Lcd = QtGui.QLCDNumber(self.Wave2)
        self.Wave2Lcd.setObjectName(_fromUtf8("Wave2Lcd"))
        self.gridLayout_4.addWidget(self.Wave2Lcd, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave2Mute = QtGui.QPushButton(self.Wave2)
        self.Wave2Mute.setStyleSheet(_fromUtf8("QPushButton#Wave2Mute:checked { background-color: red}"))
        self.Wave2Mute.setCheckable(True)
        self.Wave2Mute.setObjectName(_fromUtf8("Wave2Mute"))
        self.gridLayout_4.addWidget(self.Wave2Mute, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_4 = QtGui.QRadioButton(self.Wave2)
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setMinimumSize(QtCore.QSize(20, 20))
        self.radioButton_4.setMaximumSize(QtCore.QSize(20, 20))
        self.radioButton_4.setText(_fromUtf8(""))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_4.addWidget(self.radioButton_4, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave2Solo = QtGui.QPushButton(self.Wave2)
        self.Wave2Solo.setStyleSheet(_fromUtf8("QPushButton#Wave2Solo:checked { background-color: red}"))
        self.Wave2Solo.setCheckable(True)
        self.Wave2Solo.setObjectName(_fromUtf8("Wave2Solo"))
        self.gridLayout_4.addWidget(self.Wave2Solo, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave2Ins2 = QtGui.QDial(self.Wave2)
        self.Wave2Ins2.setMinimumSize(QtCore.QSize(40, 40))
        self.Wave2Ins2.setMaximumSize(QtCore.QSize(40, 40))
        self.Wave2Ins2.setMaximum(127)
        self.Wave2Ins2.setObjectName(_fromUtf8("Wave2Ins2"))
        self.gridLayout_4.addWidget(self.Wave2Ins2, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem10 = QtGui.QSpacerItem(20, 92, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem10, 0, 0, 1, 1)
        self.Wave2Ins1 = QtGui.QDial(self.Wave2)
        self.Wave2Ins1.setMinimumSize(QtCore.QSize(40, 40))
        self.Wave2Ins1.setMaximumSize(QtCore.QSize(40, 40))
        self.Wave2Ins1.setMaximum(127)
        self.Wave2Ins1.setObjectName(_fromUtf8("Wave2Ins1"))
        self.gridLayout_4.addWidget(self.Wave2Ins1, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave2Fader = QtGui.QSlider(self.Wave2)
        self.Wave2Fader.setMinimumSize(QtCore.QSize(0, 100))
        self.Wave2Fader.setMaximumSize(QtCore.QSize(16777215, 400))
        self.Wave2Fader.setMaximum(127)
        self.Wave2Fader.setProperty("value", 0)
        self.Wave2Fader.setOrientation(QtCore.Qt.Vertical)
        self.Wave2Fader.setProperty("channel", 0)
        self.Wave2Fader.setProperty("parameter", 0)
        self.Wave2Fader.setObjectName(_fromUtf8("Wave2Fader"))
        self.gridLayout_4.addWidget(self.Wave2Fader, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave2SubContainer = QtGui.QFrame(self.Wave2)
        self.Wave2SubContainer.setMinimumSize(QtCore.QSize(80, 150))
        self.Wave2SubContainer.setMaximumSize(QtCore.QSize(80, 150))
        self.Wave2SubContainer.setFrameShape(QtGui.QFrame.NoFrame)
        self.Wave2SubContainer.setFrameShadow(QtGui.QFrame.Plain)
        self.Wave2SubContainer.setObjectName(_fromUtf8("Wave2SubContainer"))
        self.gridLayout_12 = QtGui.QGridLayout(self.Wave2SubContainer)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.Wave2SubFader = QtGui.QSlider(self.Wave2SubContainer)
        self.Wave2SubFader.setMinimumSize(QtCore.QSize(0, 100))
        self.Wave2SubFader.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Wave2SubFader.setMaximum(127)
        self.Wave2SubFader.setOrientation(QtCore.Qt.Vertical)
        self.Wave2SubFader.setObjectName(_fromUtf8("Wave2SubFader"))
        self.gridLayout_12.addWidget(self.Wave2SubFader, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Wave2SubLcd = QtGui.QLCDNumber(self.Wave2SubContainer)
        self.Wave2SubLcd.setNumDigits(3)
        self.Wave2SubLcd.setObjectName(_fromUtf8("Wave2SubLcd"))
        self.gridLayout_12.addWidget(self.Wave2SubLcd, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.Wave2SubContainer, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Wave2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 260))
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 260))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.SysEffSubLabel = QtGui.QLabel(self.groupBox_2)
        self.SysEffSubLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.SysEffSubLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.SysEffSubLabel.setObjectName(_fromUtf8("SysEffSubLabel"))
        self.gridLayout_5.addWidget(self.SysEffSubLabel, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem11 = QtGui.QSpacerItem(35, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 1, 0, 1, 1)
        self.SysEffReturnLabel = QtGui.QLabel(self.groupBox_2)
        self.SysEffReturnLabel.setMinimumSize(QtCore.QSize(40, 40))
        self.SysEffReturnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SysEffReturnLabel.setObjectName(_fromUtf8("SysEffReturnLabel"))
        self.gridLayout_5.addWidget(self.SysEffReturnLabel, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.SysEffReturn1Led = QtGui.QRadioButton(self.groupBox_2)
        self.SysEffReturn1Led.setEnabled(False)
        self.SysEffReturn1Led.setMinimumSize(QtCore.QSize(20, 20))
        self.SysEffReturn1Led.setMaximumSize(QtCore.QSize(20, 20))
        self.SysEffReturn1Led.setText(_fromUtf8(""))
        self.SysEffReturn1Led.setObjectName(_fromUtf8("SysEffReturn1Led"))
        self.gridLayout_5.addWidget(self.SysEffReturn1Led, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.SysEffRet1 = QtGui.QDial(self.groupBox_2)
        self.SysEffRet1.setMinimumSize(QtCore.QSize(40, 40))
        self.SysEffRet1.setMaximumSize(QtCore.QSize(40, 40))
        self.SysEffRet1.setMaximum(127)
        self.SysEffRet1.setObjectName(_fromUtf8("SysEffRet1"))
        self.gridLayout_5.addWidget(self.SysEffRet1, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.SysEffSub1 = QtGui.QDial(self.groupBox_2)
        self.SysEffSub1.setMinimumSize(QtCore.QSize(40, 40))
        self.SysEffSub1.setMaximumSize(QtCore.QSize(40, 40))
        self.SysEffSub1.setMaximum(127)
        self.SysEffSub1.setObjectName(_fromUtf8("SysEffSub1"))
        self.gridLayout_5.addWidget(self.SysEffSub1, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.SysEffReturn2Led = QtGui.QRadioButton(self.groupBox_2)
        self.SysEffReturn2Led.setEnabled(False)
        self.SysEffReturn2Led.setMinimumSize(QtCore.QSize(20, 20))
        self.SysEffReturn2Led.setMaximumSize(QtCore.QSize(20, 20))
        self.SysEffReturn2Led.setText(_fromUtf8(""))
        self.SysEffReturn2Led.setObjectName(_fromUtf8("SysEffReturn2Led"))
        self.gridLayout_5.addWidget(self.SysEffReturn2Led, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.SysEffRet2 = QtGui.QDial(self.groupBox_2)
        self.SysEffRet2.setMinimumSize(QtCore.QSize(40, 40))
        self.SysEffRet2.setMaximumSize(QtCore.QSize(40, 40))
        self.SysEffRet2.setMaximum(127)
        self.SysEffRet2.setObjectName(_fromUtf8("SysEffRet2"))
        self.gridLayout_5.addWidget(self.SysEffRet2, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.SysEffSub2 = QtGui.QDial(self.groupBox_2)
        self.SysEffSub2.setMinimumSize(QtCore.QSize(40, 40))
        self.SysEffSub2.setMaximumSize(QtCore.QSize(40, 40))
        self.SysEffSub2.setMaximum(127)
        self.SysEffSub2.setObjectName(_fromUtf8("SysEffSub2"))
        self.gridLayout_5.addWidget(self.SysEffSub2, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(150, 430))
        self.groupBox_3.setMaximumSize(QtCore.QSize(150, 430))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/microphone-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_7.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setMaximumSize(QtCore.QSize(80, 25))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/speaker-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_7.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/piano-keyboard-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_7.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setMaximumSize(QtCore.QSize(80, 25))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setMaximumSize(QtCore.QSize(80, 25))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setMaximumSize(QtCore.QSize(80, 25))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 3, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/RCA-Connector-Plug-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_7.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/karaoke-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_7.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setMaximumSize(QtCore.QSize(80, 25))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(250, 250))
        self.groupBox_4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_9.addWidget(self.comboBox, 0, 0, 1, 3)
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_9.addWidget(self.label_12, 1, 0, 1, 3)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_9.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_9.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_9.addWidget(self.pushButton_8, 4, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_9.addWidget(self.lineEdit, 4, 2, 2, 1, QtCore.Qt.AlignRight)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_9.addWidget(self.pushButton_9, 5, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_9.addWidget(self.label_13, 6, 0, 1, 3)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_9.addWidget(self.pushButton_10, 7, 0, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_9.addWidget(self.pushButton_11, 8, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem13, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.outputBox = QtGui.QGroupBox(self.centralwidget)
        self.outputBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.outputBox.setObjectName(_fromUtf8("outputBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.outputBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_15 = QtGui.QLabel(self.outputBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_8.addWidget(self.label_15, 3, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.OutputWaveRecSourceSelector = QtGui.QComboBox(self.outputBox)
        self.OutputWaveRecSourceSelector.setObjectName(_fromUtf8("OutputWaveRecSourceSelector"))
        self.gridLayout_8.addWidget(self.OutputWaveRecSourceSelector, 4, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.MasterLineFader = QtGui.QSlider(self.outputBox)
        self.MasterLineFader.setMinimumSize(QtCore.QSize(0, 100))
        self.MasterLineFader.setMaximumSize(QtCore.QSize(16777215, 400))
        self.MasterLineFader.setStyleSheet(_fromUtf8(""))
        self.MasterLineFader.setMaximum(127)
        self.MasterLineFader.setProperty("value", 0)
        self.MasterLineFader.setOrientation(QtCore.Qt.Vertical)
        self.MasterLineFader.setProperty("channel", 0)
        self.MasterLineFader.setProperty("parameter", 0)
        self.MasterLineFader.setObjectName(_fromUtf8("MasterLineFader"))
        self.gridLayout_8.addWidget(self.MasterLineFader, 5, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_17 = QtGui.QLabel(self.outputBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 7, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.WaveRecFader = QtGui.QSlider(self.outputBox)
        self.WaveRecFader.setEnabled(True)
        self.WaveRecFader.setMaximum(127)
        self.WaveRecFader.setOrientation(QtCore.Qt.Vertical)
        self.WaveRecFader.setObjectName(_fromUtf8("WaveRecFader"))
        self.gridLayout_8.addWidget(self.WaveRecFader, 5, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_16 = QtGui.QLabel(self.outputBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 7, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.outputMasterSourceSelect = QtGui.QComboBox(self.outputBox)
        self.outputMasterSourceSelect.setObjectName(_fromUtf8("outputMasterSourceSelect"))
        self.gridLayout_8.addWidget(self.outputMasterSourceSelect, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_14 = QtGui.QLabel(self.outputBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.MasterLineLcd = QtGui.QLCDNumber(self.outputBox)
        self.MasterLineLcd.setObjectName(_fromUtf8("MasterLineLcd"))
        self.gridLayout_8.addWidget(self.MasterLineLcd, 6, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.WaveRecLcd = QtGui.QLCDNumber(self.outputBox)
        self.WaveRecLcd.setObjectName(_fromUtf8("WaveRecLcd"))
        self.gridLayout_8.addWidget(self.WaveRecLcd, 6, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.outputBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 870, 20))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuActions = QtGui.QMenu(self.menuBar)
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionReset_all = QtGui.QAction(MainWindow)
        self.actionReset_all.setObjectName(_fromUtf8("actionReset_all"))
        self.actionReset_Mixer = QtGui.QAction(MainWindow)
        self.actionReset_Mixer.setObjectName(_fromUtf8("actionReset_Mixer"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuActions.addAction(self.actionReset_Mixer)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_22.setText(_translate("MainWindow", "Mic/Guitar", None))
        self.label.setText(_translate("MainWindow", "Pan", None))
        self.label_18.setText(_translate("MainWindow", "Ins Eff", None))
        self.label_19.setText(_translate("MainWindow", "Send 1", None))
        self.label_20.setText(_translate("MainWindow", "Send 2", None))
        self.SubButton.setText(_translate("MainWindow", "Sub", None))
        self.label_21.setText(_translate("MainWindow", "Main", None))
        self.MicModeButton.setText(_translate("MainWindow", "INPUT", None))
        self.Mic1.setTitle(_translate("MainWindow", "Mic1/Guitar", None))
        self.Mic1Mute.setText(_translate("MainWindow", "Mute", None))
        self.Mic1Solo.setText(_translate("MainWindow", "Solo", None))
        self.label_2.setText(_translate("MainWindow", "1", None))
        self.Mic2.setTitle(_translate("MainWindow", "Mic2", None))
        self.label_3.setText(_translate("MainWindow", "2", None))
        self.Mic2Mute.setText(_translate("MainWindow", "Mute", None))
        self.Mic2Solo.setText(_translate("MainWindow", "Solo", None))
        self.Wave1.setTitle(_translate("MainWindow", "Wave1", None))
        self.Wave1Mute.setText(_translate("MainWindow", "Mute", None))
        self.Wave1Solo.setText(_translate("MainWindow", "Solo", None))
        self.label_4.setText(_translate("MainWindow", "3", None))
        self.Wave2.setTitle(_translate("MainWindow", "Wave2", None))
        self.label_5.setText(_translate("MainWindow", "4", None))
        self.Wave2Mute.setText(_translate("MainWindow", "Mute", None))
        self.Wave2Solo.setText(_translate("MainWindow", "Solo", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "System Effect", None))
        self.SysEffSubLabel.setText(_translate("MainWindow", "Sub", None))
        self.SysEffReturnLabel.setText(_translate("MainWindow", "Return", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Easy Setting", None))
        self.label_8.setText(_translate("MainWindow", "Use Mic 1", None))
        self.label_7.setText(_translate("MainWindow", "Listen", None))
        self.label_9.setText(_translate("MainWindow", "Use Line", None))
        self.label_10.setText(_translate("MainWindow", "Eff Loop", None))
        self.label_11.setText(_translate("MainWindow", "Karaoke", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Effect", None))
        self.label_12.setText(_translate("MainWindow", "Insertion Effect", None))
        self.pushButton_6.setText(_translate("MainWindow", "Mic1", None))
        self.pushButton_7.setText(_translate("MainWindow", "Mic2", None))
        self.pushButton_8.setText(_translate("MainWindow", "Wave1", None))
        self.pushButton_9.setText(_translate("MainWindow", "Wave2", None))
        self.label_13.setText(_translate("MainWindow", "System Effect", None))
        self.pushButton_10.setText(_translate("MainWindow", "Sys1", None))
        self.pushButton_11.setText(_translate("MainWindow", "Sys2", None))
        self.outputBox.setTitle(_translate("MainWindow", "Output", None))
        self.label_15.setText(_translate("MainWindow", "Source Select", None))
        self.label_17.setText(_translate("MainWindow", "WAVE (REC)", None))
        self.label_16.setText(_translate("MainWindow", "MASTER", None))
        self.label_14.setText(_translate("MainWindow", "Source Select", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuActions.setTitle(_translate("MainWindow", "Actions", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionReset_all.setText(_translate("MainWindow", "Reset all", None))
        self.actionReset_Mixer.setText(_translate("MainWindow", "Reset Mixer", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

